### ISSUE TITLE
coffee server.coffee --nodejs --> process.EventEmitter is not a constructor

### ISSUE THREAD

**Issue by nowox** [outsideris/popularconvention#69]
I did:

```
$ git clone https://github.com/outsideris/popularconvention.git
$ cd popularconvention
$ npm install 
audited 253 packages in 2.032s
found 43 vulnerabilities (17 low, 12 moderate, 14 high)
  run `npm audit fix` to fix them, or `npm audit` for details

$ bower install

$ coffee server.coffee --nodejs
TypeError: process.EventEmitter is not a constructor
    at Object.<anonymous> (/popularconvention/node_modules/restler/lib/restler.js:91:21)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/popularconvention/src/timeline.coffee:4:13)
    at Object.<anonymous> (/popularconvention/src/timeline.coffee:69:4)
```

I also tried to write a `docker-compose`: 

```yaml
version: "2"

services:
  websever:
    build:
      context: .
    volumes:
      - ./:/home/
    ports:
      - 8020:8020
    links:
      - mongo
  mongo:
    build:
      context: ./data/
    volumes:
      - ./data/:/home
```

Which with I get this: 

```
$ docker-compose up
Starting popularconvention_mongo_1 ...
Starting popularconvention_mongo_1 ... done
Starting popularconvention_websever_1 ...
Starting popularconvention_websever_1 ... done
Attaching to popularconvention_mongo_1, popularconvention_websever_1
websever_1  | SyntaxError: Block-scoped declarations (let, const, function, class) not yet supported outside strict mode
websever_1  |   at exports.runInThisContext (vm.js:53:16)
...
websever_1  |   at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/coffee-script.js:119:23)
websever_1  |   at compileScript (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:207:29)
websever_1  |   at compilePath (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:160:14)
websever_1  |   at Object.exports.run (/usr/local/lib/node_modules/coffee-script/lib/coffee-script/command.js:95:21)
websever_1  |   at Object.<anonymous> (/usr/local/lib/node_modules/coffee-script/bin/coffee:7:41)
websever_1  |   at Module._compile (module.js:409:26)
websever_1  |   at Object.Module._extensions..js (module.js:416:10)
websever_1  |   at Module.load (module.js:343:32)
websever_1  |   at Function.Module._load (module.js:300:12)
websever_1  |   at Function.Module.runMain (module.js:441:10)
websever_1  |   at startup (node.js:140:18)
websever_1  |   at node.js:1043:3
websever_1  |
mongo_1     | 2019-01-24T09:14:24.542+0000      building a list of dbs and collections to restore from /home/dump dir
mongo_1     | 2019-01-24T09:14:24.546+0000      cannot drop system collection popular_convention2.system.users, skipping
mongo_1     | 2019-01-24T09:14:24.546+0000      reading metadata file from /home/dump/popular_convention2/system.users.metadata.json
mongo_1     | 2019-01-24T09:14:24.547+0000      reading metadata file from /home/dump/popular_convention2/conventions.metadata.json
mongo_1     | 2019-01-24T09:14:24.547+0000      reading metadata file from /home/dump/popular_convention2/score.metadata.json
mongo_1     | 2019-01-24T09:14:24.548+0000      reading metadata file from /home/dump/popular_convention2/worklogs.metadata.json
...
mongo_1     | 2019-01-24T09:14:24.679+0000      finished restoring popular_convention2.score (2291 documents)
mongo_1     | 2019-01-24T09:14:24.690+0000      done
popularconvention_websever_1 exited with code 1
```

Is someone experiencing the same issues?

**Comment by outsideris** [comment]
Did you try with [docker images](https://github.com/outsideris/popularconvention#docker). I made it with node v4, so it is too old.
